### ISSUE TITLE
[Local Editor] Tokens are getting passed back from other prompts / previous executions unexpectedly

### ISSUE THREAD

**Issue by jonathanlastmileai** [lastmile-ai/aiconfig#1108]
I have a cell like this:

```
echo tokens precisely
#SECTION DATA
{{context}}
#END DATA SECTION
```

When I run it, I get back previous outputs from other cells. I expected to only get back the contents of "context". 

This seems to happen even if I clear outputs and restart the server.

**Comment by Ankush-lastmile** [comment]
Resolved offline, This issue is mitigated by setting `remember_chat_context` to false under prompt metadata.
