### ISSUE TITLE
Add error message for unfound model name

### ISSUE THREAD

**Issue by rossdanlm** [lastmile-ai/aiconfig#1136]
We have similar message for unfound Prompt names. Inspired by changes in https://github.com/lastmile-ai/aiconfig/pull/1114#discussion_r1478635688

Similar to https://github.com/lastmile-ai/aiconfig/blob/main/python/src/aiconfig/Config.py#L389C70-L389C121

**Comment by Ankush-lastmile** [comment]
Implemented in #1475
