### ISSUE TITLE
python version >=3.10 is required, 3.9 receives error

### ISSUE THREAD

**Issue by erdemunal35** [lastmile-ai/aiconfig#1143]
Hi,
I receive the error below when the python version of the virtual environment I install aiconfig is 3.9
<img width="1160" alt="Screenshot 2024-02-06 at 08 46 50" src="https://github.com/lastmile-ai/aiconfig/assets/46455260/9a872d39-d47e-42f3-aca3-bc77fe64296c">

when I use 3.10 it works fine. Can we say/add python version >=3.10 is required to the README.md?

Best,
Erdem

**Comment by saqadri** [comment]
Thanks for reporting @erdemunal35! @Ankush-lastmile or @jonathanlastmileai can you PTAL?

**Comment by rossdanlm** [comment]
Hey Erdem, we updated the pyprojects to all require `>=3.10` in https://github.com/lastmile-ai/aiconfig/pull/1146! Also made a note of this in our changelog (https://github.com/lastmile-ai/aiconfig/releases/tag/v1.1.20) and this is not fixed in `v1.1.20` for the main `python-aiconfig` library!
