### ISSUE TITLE
run failed: import Mapping and other collection classes from collections.abc instead of collections

### ISSUE THREAD

**Issue by elwhittle** [lastmile-ai/aiconfig#1372]
Summary: `jsonspec/pointer/base.py` and `jsonspec/pointer/stages.py` have an import bug. To fix this, the files need to import Mapping, Sequence, and Set from collections.abc instead of from collections.

While at the RAG + Eval workshop, the VSCode extension for `rag.aiconfig.yaml` would not work. The output error was that the Mapping class was being imported from the wrong place. Working in my virtual environment, I modified the import lines in `.venv/lib/python3.10/site-packages/jsonspec/pointer/stages.py` and `.venv/lib/python3.10/site-packages/jsonspec/pointer/bases.py` as follows:

 ```python
# from collections import Mapping, Sequence, MutableSequence
from collections.abc import Mapping, Sequence, MutableSequence
```

I tried this on Python 3.9, 3.10, and 3.11. 3.9 didn't work at all, and both 3.10 and 3.11 needed the change. I'm running on Apple Silicon, and I got my Pythons from brew.

The output log is below.

```sh
 File "/Users/el/Programming/aiconfig/cookbooks/RAG-with-Model-Graded-Eval-v2/.venv/lib/python3.10/site-packages/jsonspec/pointer/stages.py", line 7, in <module>
    from collections import Mapping, Sequence, Set
ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

**Comment by elwhittle** [comment]
This appears to just be an issue with json-spec, which seems to be fixed in the source code. I'm not sure why the code isn't up to date in the env I used.

**Comment by rossdanlm** [comment]
>This appears to just be an issue with json-spec, which seems to be fixed in the source code

Thanks for sharing El! I think perhaps your env setup may have been created on an older release? I'm going to close this issue but really appreciate the detail and thoroughness you provided! Do you want to come meet at our office sometime? Pls feel free to message me on linked in and we can follow up if you're interested: https://www.linkedin.com/in/rossdancraig/ :)
