### ISSUE TITLE
rag_demo.ipynb Eval with trials generate_trials_for_eval missing argument

### ISSUE THREAD

**Issue by sandeepnmenon** [lastmile-ai/aiconfig#1373]
In the [rag_demo.ipynb](https://github.com/lastmile-ai/aiconfig/blob/main/cookbooks/RAG-with-Model-Graded-Eval-v2/rag_demo.ipynb) , function `generate_trials_for_eval`, the `generate` function does not have the `prompt` argument.

Is fix to just add the `generate` prompt
```python
async def generate_trials_for_eval(query, context, trials):
    outputs = []
    for _ in range(trials):
        result = await generate(query, context, prompt="generate")
        outputs.append(result)

    return outputs
```

**Comment by saqadri** [comment]
Thanks for reporting, @sandeepnmenon! Fixed in #1378
