### ISSUE TITLE
System prompts attached to the model parser level does not appear in the editor

### ISSUE THREAD

**Issue by andrew-lastmile** [lastmile-ai/aiconfig#1391]
Problem: it's difficult to debug issues with prompts within the editor since there is no way to find the system prompt that might be attached to the model level. The local system prompt at the cell level adds an extra layer of confusion.

Editor view:
<img width="1131" alt="image" src="https://github.com/lastmile-ai/aiconfig/assets/129882602/216a9b41-2fa4-4e73-b4bb-d33c1553da9d">

Raw JSON:
<img width="714" alt="image" src="https://github.com/lastmile-ai/aiconfig/assets/129882602/ae2cb6bc-1a00-434e-8981-6391acbed4ec">

**Comment by rholinshead** [comment]
Ya, we had decided on not surfacing global metadata in the UI for editor MVP but should think about the ideal UX for this now. This should also include 'default_model' and the model_parsers mapping in the global metadata

(super rough draft, WIP, just adding as accordion item):
![Screenshot 2024-03-04 at 4 48 38 PM](https://github.com/lastmile-ai/aiconfig/assets/5060851/7d849f0a-8f00-4973-9ace-f9a1f80b8aa4)
