### ISSUE TITLE
[editor] Add button to clear single prompt output

### ISSUE THREAD

**Issue by rossdanlm** [lastmile-ai/aiconfig#1451]
Today we have a button to clear all outputs, but it would be great to have something that adds to a single one only.

https://github.com/lastmile-ai/aiconfig/assets/151060367/241b1f38-0295-4550-9a4f-5804f487ab2d

Goals:
1. Get familiar with the AIConfig SDK (you'll learn the schema structure (in schema.py file) as well as SDK API (Config.py + schema.py)
2. Some familiarity with our editor and how it attaches to server and calls into our SDK API to execute operations

## Testing

First must need  to pip install to local repo
You will need to make sure you're on Python 3.10 or higher
`cd aiconfig/python && pip3 install -e .`
`cd aiconfig/extensions/HuggingFace/python && pip3 install -e .`

The only way to test this is through local editor because that will have your local changes connected!

Go to `aiconfig/python/src/aiconfig/editor/client` and run this command (you need to re-run this every time you make changes in the `aiconfig/python/src/aiconfig/editor/client` directory!):
```
rm -rf node_modules && yarn && yarn build
```

Then go to `aiconfig` dir and run this command:
```
aiconfig_path=./cookbooks/Gradio/huggingface.aiconfig.json
parsers_path=./cookbooks/Gradio/aiconfig_model_registry.py
aiconfig edit --aiconfig-path=$aiconfig_path --server-port=8080 --server-mode=debug_servers --parsers-module-path=$parsers_path
```

**Comment by rholinshead** [comment]
> you need to re-run this every time you make changes in the aiconfig/python/src/aiconfig/editor/client directory!

Note that hot reloading will pick up local changes; you only need to run this to build the js for the --server-mode=prod variant (i.e. must build before publishing aiconfig package)
