### ISSUE TITLE
option to add a list of outputs to config

### ISSUE THREAD

**Issue by Ankush-lastmile** [lastmile-ai/aiconfig#153]
add_output takes in a single output, it would be nice to add a list of outputs at once

**Comment by sp6370** [comment]
@tanya-rai @Ankush-lastmile!
I would like to pick this up. Can I have some more context for the issue?

**Comment by tanya-rai** [comment]
Amazing! Yeah you be able to. @Ankush-lastmile will provide some context today so you can get started.

**Comment by sp6370** [comment]
@Ankush-lastmile Any context on this?

**Comment by Ankush-lastmile** [comment]
Hey @sp6370, thanks for following up on this! I apologize for the delay. I've been tied up with a few other tasks. I'll make sure to provide you with the necessary context by the end of the day so you can start working on the issue. Thanks for your patience!

**Comment by sp6370** [comment]
@Ankush-lastmile No worries! Please take your time.

**Comment by Ankush-lastmile** [comment]
Hi @sp6370! Apologies for the delay in getting back to you.

You can find the current method definition of `add_output` method [in schema.py](https://github.com/lastmile-ai/aiconfig/blob/5cce4ebd8eec70222f3fb7560e4c3343b5a9ee95/python/src/aiconfig/schema.py#L511)  

As you can see, this method currently accepts a single output. The goal is to extend its functionality to handle multiple outputs. A possible approach is to introduce a new method, add_outputs, which would be similar in design to add_output. However, instead of a single output, it would accept a list of outputs. This method would then iterate over the list, utilizing `add_output` for each individual item.


Looking forward to your thoughts and contributions on this! Please feel free to reach out if you have any questions or need further clarification.

**Comment by sp6370** [comment]
@Ankush-lastmile Could you elaborate what does not output do here?
https://github.com/lastmile-ai/aiconfig/blob/main/python/src/aiconfig/schema.py#L533

As per my understanding `not output` => User hasn't given anything to add to the prompt output. In that case, the function should just exit. 

In the current case, if the output is just empty, then it adds the None value to the prompt output.

Is there something that I am missing here?

**Comment by Ankush-lastmile** [comment]
Great observation, @sp6370! Your understanding seems correct – if 'output' is non-existent, it ideally shouldn't proceed to add anything to 'prompt.outputs'. Exiting the function or raising an error in this scenario would be a more appropriate action. 

This does look like a potential oversight in our current implementation. Your eye for this detail is much appreciated! We should consider addressing this as part of the enhancement. Would recommend that we throw an exception here if Output is None considering the fact that the Output object being passed in is _not_ optional.

**Comment by sp6370** [comment]
Gotchya! Could you go ahead and create a issue for this and assign to me?
For the this issue, I will implement error handling as discussed above and raise the PR later today.

**Comment by Ankush-lastmile** [comment]
>Could you go ahead and create a issue for this and assign to me?

Great! Created #529 

I'm unable to assign your user to the issue for some reason at the moment

**Comment by sp6370** [comment]
@Ankush-lastmile I have sent you a message over Discord. Could you have a look at my request?

**Comment by sp6370** [comment]
I can't seem to get the `add_output` working. 

```python
import os
from aiconfig import AIConfigRuntime
import aiconfig_extension_gemini
from aiconfig.schema import ExecuteResult

os.environ['GOOGLE_API_KEY'] = ""

config = AIConfigRuntime(**{
    "name": "Exploring Gemini",
    "description": "",
    "schema_version": "latest",
    "metadata": {
        "models": {
            "gemini-pro": {
                "stream": True
            }
        },
        "default_model": "gemini-pro",
        "model_parsers": {}
    },
    "prompts": [
        {
            "name": "multilinguality",
            "input": "Can you teach me how to say duck in Mexican?",
            "metadata": {
                "model": "gemini-pro",
                "remember_chat_context": False
            }
        },
        {
            "name": "pronounciation",
            "input": "Can you explain how to pronounce the {{language}} one?",
            "metadata": {
                "model": "gemini-pro",
                "remember_chat_context": False
            }
        }
    ]
})

config.save("gemini_demo.aiconfig.json")

from aiconfig import CallbackManager, InferenceOptions
aiconfig = AIConfigRuntime.load("gemini_demo.aiconfig.json")

test_result = ExecuteResult(
    output_type="execute_result",
    execution_count=0.0,
    data={"role": "assistant", "content": "test output"},
    metadata={"finish_reason": "stop"},
)

aiconfig.add_output("multilinguality", test_result)

#aiconfig.delete_output("multilinguality")
await aiconfig.run("multilinguality")
output_text = aiconfig.get_output_text("multilinguality")
print(f'Gemini output: {output_text} \n')
```

Output:
<img width="916" alt="image" src="https://github.com/lastmile-ai/aiconfig/assets/26037101/51c961ba-9f21-46c7-b92d-6de62b94a544">

Expected Output:
`Gemini output: Pato test output`

Can you let me know what I am missing here?

**Comment by sp6370** [comment]
@Ankush-lastmile Any thoughts on How should I go about resolving this?

**Comment by Ankush-lastmile** [comment]
> Any thoughts on How should I go about resolving this?


I noticed your approach with the run() method in the code.  `run()` clears any previous outputs each time it's executed.

One thing you could try is adjusting the sequence of your operations. I would reccomend trying to either add the output after executing run or see if you can achieve your goal without using run at all initially.

Here's some pseudocode to illustrate:
```
output = ExecuteResult(...)
aiconfig.add_output("multilinguality", output)

print(aiconfig.get_prompt("multilinguality")) # print prompt. Should have new output added
```

This might help in better understanding how your changes are affecting the output. Give it a shot and let me know your findings!
