### ISSUE TITLE
Output display with streaming

### ISSUE THREAD

**Issue by tanya-rai** [lastmile-ai/aiconfig#287]
Output displays prompt response + ExecuteResult obj. Feels a little repetitive. Shown in image (gets messier when output is longer). 

For chained prompts, streaming shows the previous prompt responses which makes sense but if there was some demarcation  on the output corresponding to the prompt name that would be helpful. Otherwise it gets hard to read. 
[
<img width="963" alt="Screenshot 2023-11-19 at 12 54 35 AM" src="https://github.com/lastmile-ai/aiconfig/assets/81494782/fb28c208-89c2-45e0-9130-69715231516a">
](url)

**Comment by saqadri** [comment]
I think in that code if you set result = await config.run(...), it wont print it to console? Output isn't automatically printed to console (only the stream is), the notebook is printing the object I believe because it isn't assigned to a variable
