### ISSUE TITLE
Support AIConfig format lint/validation in VS Code editor

### ISSUE THREAD

**Issue by rholinshead** [lastmile-ai/aiconfig#292]
Depends on https://github.com/lastmile-ai/aiconfig/issues/291

As a major devX nicety, we should consider leveraging the schema we defined for https://github.com/lastmile-ai/aiconfig/issues/291 to apply in VS Code so that it provides linting of the config JSON file structure to match the schema. See https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings for info. Looks like it supports either defining via a $schema key in the JSON itself (would need to add that to the spec, but might be nice anyway to have automatic validation in VS Code as well as a form of versioning of the schema) or can have it as a setting based on file path/name/etc. (might make sense to have a common naming like .aiconfig.json in that case).

**Comment by rholinshead** [comment]
When serializing a config to disk, we may want to include this schema value as well so that the saved config is immediately linted in VS Code

**Comment by rholinshead** [comment]
See some discussion in https://github.com/lastmile-ai/aiconfig/pull/299

**Comment by saqadri** [comment]
This is done as part of adding aiconfig schema to schema store
