### ISSUE TITLE
Missing attribute `model_dump`

### ISSUE THREAD

**Issue by andrew-lastmile** [lastmile-ai/aiconfig#331]
Hitting an issue within cookbooks in regards to missing attribute `model_dump`

`[/usr/local/lib/python3.10/dist-packages/aiconfig/default_parsers/openai.py](https://localhost:8080/#) in run_inference(self, prompt, aiconfig, options, parameters)
    269             for chunk in response:
    270                 # OpenAI>1.0.0 uses pydantic models. Chunk is of type ChatCompletionChunk; type is not directly importable from openai Library, will require some diffing
--> 271                 chunk = chunk.model_dump(exclude_none=True)
    272                 # streaming only returns one chunk, one choice at a time (before 1.0.0). The order in which the choices are returned is not guaranteed.
    273                 messages = multi_choice_message_reducer(messages, chunk)

AttributeError: 'dict' object has no attribute 'model_dump'`

**Comment by saqadri** [comment]
Is this fixed now with #334 @Ankush-lastmile @jonathanlastmileai ?

**Comment by Ankush-lastmile** [comment]
Yes this is fixed with #334
