### ISSUE TITLE
[local editor] support specifying index in addPrompt

### ISSUE THREAD

**Issue by rholinshead** [lastmile-ai/aiconfig#357]
Currently, new prompts are added to the end of the prompts list in the config. We should update the addPrompt method to support an optional index into which the new prompt should be inserted. This will be useful for a few things:

1. Local editor / UI representations should support adding prompts / cells in different locations in the editor, instead of just at the bottom
2. For things like dependencies, conversation history, we are currently relying on the ordering of previous prompts in the list before the current prompt. If we want to add a new dependency or conversation message above the current prompt, we would currently need to remove and re-add all prompts up to that point. Instead, we should be able to just insert a new prompt at the desired index for this purpose

**Comment by saqadri** [comment]
Just adding the local-editor tag to make sure we can prioritize accordingly

**Comment by suyoglastmileai** [comment]
This is probably pri: high since this blocks local editor from adding prompts in between other prompts without a fn like this.

**Comment by rossdanlm** [comment]
Fixed in https://github.com/lastmile-ai/aiconfig/pull/599
