### ISSUE TITLE
Remove PromptWithOutputs Type

### ISSUE THREAD

**Issue by rholinshead** [lastmile-ai/aiconfig#365]
The definition is
```
export type PromptWithOutputs = Prompt & { outputs?: Output[] };
```
But the definition for `Prompt` already contains
```
  /**
   * Execution, display, or stream outputs.
   */
  outputs?: Output[];
```

So `PromptWithOutputs` is redundant and can be removed and replaced by just `Prompt`

**Comment by rossdanlm** [comment]
Closed because fixed in https://github.com/lastmile-ai/aiconfig/pull/508
