### ISSUE TITLE
LLM Consistency Cookbook is buggy

### ISSUE THREAD

**Issue by 2timesjay** [lastmile-ai/aiconfig#374]
Four bugs, present in both Colab and Local (vscode jupyter notebook) runs
1. references "multi-llm-consistency.json", there is a similar file with underscores available but nothing matching this.
2. multi_llm_consistency_json aliases its model names. This doesn't work. "ChatGPT" is never added to the ModelRegistry, so you get the error below
3. palm doesn't work - I assume this is a config issue on my end but I didn't see a solution at a glance. What's expected behavior when one model type is unconfigured?
4. `run_with_dependencies` is false by default, so the run doesn't work when the above issues are fixed.

Here's a fixed NB: https://colab.research.google.com/drive/199HTWPv5BdU5hhX5IC474pV8RNXtKFB2#scrollTo=ZhyBEWGcM6zB, though palm still doesn't work.

Error from #2:
```
[/usr/local/lib/python3.10/dist-packages/aiconfig/registry.py](https://localhost:8080/#) in get_model_parser(model_id)
     39             ModelParser: The retrieved model parser
     40         """
---> 41         return ModelParserRegistry._parsers[model_id]
     42 
     43     @staticmethod

KeyError: 'ChatGPT'
```

**Comment by jonathanlastmileai** [comment]
@2timesjay , thanks for the issue! I'll look at this with @Ankush-lastmile today. cc @saqadri

**Comment by jonathanlastmileai** [comment]
It looks like @Ankush-lastmile 's PR fixes this locally - thanks for the suggestion, @2timesjay ! We'll merge that soon. Also WIP: colab fix.

**Comment by Ankush-lastmile** [comment]
Hey @2timesjay thanks for finding this, Looks like this cookbook was outdated. I just merged a pr that fixes the cookbook, including your fix for the "ChatGPT" key  - Thanks for that, also added a fix for executing the PaLM cell

Not sure if you're familiar with Google's PaLM, just make sure you get an api key from here https://developers.generativeai.google/products/palm

**Comment by jonathanlastmileai** [comment]
@Ankush-lastmile just checking, which PR fixes the colab?
