### ISSUE TITLE
Support N-Arbitrary inputs in AIConfig Schema

### ISSUE THREAD

**Issue by Ankush-lastmile** [lastmile-ai/aiconfig#417]
Currently AIConfig has a focus on text based inputs. Models such as GPT-4-vision allow arbitrary text and image inputs.

See https://github.com/lastmile-ai/lastmile/pull/1333 for a sample impl to build off of WIP #360

**Comment by saqadri** [comment]
This is completed with the work to add attachments to the aiconfig schema (thanks @rholinshead)
