### ISSUE TITLE
[bug] HuggingFace Model Parser in Python is missing the dependency to resolve_prompt

### ISSUE THREAD

**Issue by andrew-lastmile** [lastmile-ai/aiconfig#442]
`resolved_prompt = resolve_prompt(prompt, params, aiconfig)` - resolve_prompt is undefined. `resolve_prompt` was moved into `python/src/aiconfig/util/params.py`, but the import is still referencing `aiconfig.util.config_utils`.

**Comment by saqadri** [comment]
Should be a quick 5 minute change -- @Ankush-lastmile?

**Comment by jonathanlastmileai** [comment]
Thanks @Ankush-lastmile. Did we blame the removed import?

**Comment by saqadri** [comment]
> @andrew-lastmile , how did you discover this?

@jonathanlastmileai, Andrew was making a cookbook.

This has been fixed now
