### ISSUE TITLE
How should we store high memory objects (ex: images) in AIConfig?

### ISSUE THREAD

**Issue by rossdanlm** [lastmile-ai/aiconfig#468]
Can take up quite a lot of space/memory. Ex: Diffusion XL model output in https://github.com/lastmile-ai/aiconfig/pull/460#issuecomment-1851376017 is 1.36 MB, 1,424,248 chars. Look at how long the output field is for a 1.4M-character string for 64-bit encoding in https://raw.githubusercontent.com/lastmile-ai/aiconfig/e56d719110aa9b4c5b3f36040ee1c533995e02fa/cookbooks/Getting-Started/new.aiconfig.json (testing diff in https://github.com/lastmile-ai/aiconfig/pull/461)

This also comes with @jonathanlastmileai's comment that AIConfig should have settings separated from the input + outputs

**Comment by rholinshead** [comment]
Our own implementation should only ever store urls to data and we should be opinionated about recommending that to developers implementing their own parsers as well. Storing raw image/video/etc. data in the config is going to cause a lot of problems around perf, versioning/review, etc.

**Comment by saqadri** [comment]
I think this question is resolved -- closing the issue, but please reopen if needed.
