### ISSUE TITLE
Should all the Gradio HF models be separate extensions or all within the same HF extension?

### ISSUE THREAD

**Issue by rossdanlm** [lastmile-ai/aiconfig#480]
Ex: we're going to support 5 different model parsers:

- [DONE] TextGeneration
- TextTranslation
- TextSummarization
- [DONE] Text2Image
- Text2Speech

**Comment by saqadri** [comment]
A single HF extension makes sense to me for aiconfig

**Comment by rholinshead** [comment]
IMO it makes sense to have them separate instead of one monolithic extension. Each one may use some different library under the hood (e.g. diffusers vs transformers) that don't need to be there for each extension, and may have different capabilities. For example, if we need to associate the TextAndImageToText model parser with an input schema that supports image/png attachments then that necessarily means the TextAndImageToText models need to have their own model parser whose input schema defines input text and image attachment mimetype

**Comment by rholinshead** [comment]
> IMO it makes sense to have them separate instead of one monolithic extension. Each one may use some different library under the hood (e.g. diffusers vs transformers) that don't need to be there for each extension, and may have different capabilities. For example, if we need to associate the TextAndImageToText model parser with an input schema that supports image/png attachments then that necessarily means the TextAndImageToText models need to have their own model parser whose input schema defines input text and image attachment mimetype

Ah wait, I misread and was conflating extension with model parser. I think one extension is fine, but definitely different model parsers per 'task'

**Comment by saqadri** [comment]
Can this be closed, @rossdanlm?

**Comment by rossdanlm** [comment]
Ok moving forward, we should probably have a single extension for all of hugging face. These are split into two general forms:

1. InferenceClient (the API call does the processing): https://github.com/lastmile-ai/aiconfig/tree/main/extensions/HuggingFace (ex: can rename to `HuggingFaceRemoteInferenceClient`
2. Transformers + Diffusors (we download the models and run them locally): https://github.com/lastmile-ai/aiconfig/tree/main/extensions/HuggingFaceTransformers (can rename probably to something like `HuggingFaceLocalInference`)

cc @rholinshead , @Ankush-lastmile , @saqadri let me know if you have any concerns on merging or would like to continue keeping them separate? If you don't by EOD I will create another task to unify the two separate HF extension packages that we currently have

**Comment by rossdanlm** [comment]
Followed offline, we are going to merge into 1 extension. Working on that now
