### ISSUE TITLE
[Eval] Support llm-based metrics that "compile" a function calling prompt from a metric and description

### ISSUE THREAD

**Issue by jonathanlastmileai** [lastmile-ai/aiconfig#481]
Context: https://github.com/lastmile-ai/aiconfig/issues/402

> A great-to-have would be llm-based metrics that "compile" a function calling prompt from a metric and description.

> If I'm understanding this correctly, you want to describe a metric in natural language and get a runnable metric object that uses an LLM to take the input data along with your description, and outputs some evaluation? Maybe an example?

> It can be a little less general.
e.g. consider this function spec that just enforces an output format with a dummy "log_evaluations" function.
```
  tools = [
      {
          "type": "function",
          "function": {
              "name": "log_evaluations",
              "description": "Submit ratings that apply to a piece of text",
              "parameters": {
                  "type": "object",
                  "properties": {
                      "conciseness_rating": {
                          "type": "int",
                          "description": "a 1 to 10 rating of the text's conciseness, 1 being way too verbose, 10 being very concise.",
                      },
                      "conciseness_reasoning": {"type": "string", "description": "reasoning behind the conciseness rating"]},                      
                      "conciseness_confidence": {"type": "float", "description": "0 to 1.0 rating of confidence in conciseness rating"]},
                  },
                  "required": ["conciseness_rating"],
              },
          },
      }
  ]
```
There's a lot of ways to generate this from a much more compact description, like
generate_llm_evaluation(metric_name: str, metric_description: str, auxiliary_metrics: List[Tuple[str, description]]). even if the auxiliary metrics like "reasoning" and "confidence" aren't automatically generated and described at least all the function calling cruft is avoided.

cc @2timesjay, @saqadri, @tanya-rai

**Comment by jonathanlastmileai** [comment]
@2timesjay, this PR allows you to define a custom model-graded eval metric like this:

```

import lastmile_utils.lib.core.api as core_utils

class TextRatingsData(core_utils.Record):
    conciseness_rating: int
    conciseness_confidence: float
    conciseness_reasoning: str
    
    
gpt3_5_text_ratings = make_openai_structured_llm_metric(
    eval_llm_name="gpt-3.5-turbo-0613",
    pydantic_basemodel_type=TextRatingsData,
    metric_name="text_ratings",
    metric_description="Text ratings",
    field_descriptions=dict(
        conciseness_rating="1 to 5 rating of conciseness",
        conciseness_confidence="0 to 1.0 rating of confidence in conciseness rating",
        conciseness_reasoning="reasoning behind the conciseness rating",
    ),
)
```


This is a admittedly a bit clunky/verbose, but it is very flexible and I think easy to configure, and it transparently guarantees a correctly-structured response.

Let me know what you think!


cc @saqadri , @tanya-rai

**Comment by 2timesjay** [comment]
Thanks, Will take a look at this. I think it looks quite nice. I'm glad it uses pydantic too since that should make it easier to convert between AIConfig prompts and similar constructs from other frameworks (in particular [DSPY signatures](https://github.com/stanfordnlp/dspy?tab=readme-ov-file#3-two-powerful-concepts-signatures--teleprompters) )

**Comment by saqadri** [comment]
Any updates on this issue? @jonathanlastmileai

**Comment by jonathanlastmileai** [comment]
As per my understanding, this was completed with #513. I'll close.
