### ISSUE TITLE
[bug] saving outputs in the config by default

### ISSUE THREAD

**Issue by tanya-rai** [lastmile-ai/aiconfig#490]
everytime i rerun a prompt with a new parameter I get this "apologies for the confusion, here is the updated response" 
it's because we save the output by default to the prompt which it then uses in context? 

the fix I need to do in the cookbook/streamlit app is to add this line of code always to make sure the output is deleted manually after config.run: 
`config.get_prompt("get_activities").outputs = []`

**Comment by saqadri** [comment]
This is because we aren't deleting the output before running. @Ankush-lastmile this should be a one-line fix. Can you please ship it? https://github.com/lastmile-ai/aiconfig/pull/371

**Comment by Ankush-lastmile** [comment]
Closed with #491
