### ISSUE TITLE
Update Python SDK to support openai 1.5.0

### ISSUE THREAD

**Issue by Ankush-lastmile** [lastmile-ai/aiconfig#519]
pr #518 pinned the python sdk's dependency of openai to < 1.5

OpenAI 1.5.0 introduced a new field to the chat completion response object

1. Investigate what the impact of this new field is.

2. Make changes to the OpenAI Model Parser as necessary to support this update, as well as any tests.

3. unpin or allow new version from python sdk

**Comment by rholinshead** [comment]
Closed with 1.13.3
