### ISSUE TITLE
Do not overwrite outputs in `add_output` if value passed is None

### ISSUE THREAD

**Issue by Ankush-lastmile** [lastmile-ai/aiconfig#529]
In the Python SDK, the add_output method currently contains a critical flaw. 

As observed at [this link](https://github.com/lastmile-ai/aiconfig/blob/62c8e7d664fb9fa5bc52168937406d738ece3b37/python/src/aiconfig/schema.py#L663), the method erroneously overwrites the prompt's output, even in scenarios where the Output parameter is None. This behavior contradicts the method's design, as Output is not intended to be an optional attribute. 

To align with the intended functionality, the method should be modified to raise an exception when Output is None, ensuring robust and predictable behavior.

**Comment by saqadri** [comment]
I don't fully understand the issue. Can you describe what's expected vs. actual behavior with an example?

**Comment by Ankush-lastmile** [comment]
Looks like added code changed the expected path of the link. Updated

> I don't fully understand the issue. Can you describe what's expected vs. actual behavior with an example?

The issue is that add_output incorrectly adds None to the output list when output = None is passed. The expected behavior is for the method to reject None as an invalid Output, not add it (or alternatively raise an exception). The current implementation doesn't align with this expectation.

**Comment by sp6370** [comment]
Here's a link to my original discussion with @Ankush-lastmile about this. 
https://github.com/lastmile-ai/aiconfig/issues/153#issuecomment-1859596880
