### ISSUE TITLE
[bug] aiconfig generated from workbooks adds "system_prompt": null

### ISSUE THREAD

**Issue by tanya-rai** [lastmile-ai/aiconfig#535]
Created prompts in a workbook (not using system prompt but changed temperature). Downloaded the aiconfig from the workbook and this is what the aiconfig had in model metadata. It gives me an error and only is fixed when I removed the system_prompt setting. Assuming cuz its set to null. 

```
{
  "name": "OpenAI Prompt Engineering Guide",
  "schema_version": "latest",
  "metadata": {
    "models": {
      "gpt-4": {
        "model": "gpt-4",
        "top_p": 1,
        "temperature": 0,
        "system_prompt": null,
        "presence_penalty": 0,
        "frequency_penalty": 0
      }
    },
    "parameters": {
      "original_prompt": "testing"
    }
  },
```

**Comment by saqadri** [comment]
This is fixed, right @Ankush-lastmile @rossdanlm ?

**Comment by rossdanlm** [comment]
Yea we can close this from https://github.com/lastmile-ai/aiconfig/pull/542. I added more generalized task in https://github.com/lastmile-ai/aiconfig/issues/543
