### ISSUE TITLE
Consider a YAML file format

### ISSUE THREAD

**Issue by saqadri** [lastmile-ai/aiconfig#568]
Currently AIConfig serializes to JSON -- it may be worth considering a YAML serialization as well (while enforcing the same schema) for better readability and diff'ing

**Comment by ranjancse26** [comment]
True, I was about to post an issue :)

YAML is much better with the human readability. It's good to have the support for JSON as well as YAML by default. The aiconfig could be designed to set or accept which ever applicable format for the execution purposes.

**Comment by saqadri** [comment]
This is completed in #583 and will be part of the next release.
We are still defaulting to saving as JSON schema, but you can now both load and save aiconfig as YAML:

```
from aiconfig import AIConfigRuntime

# translate JSON to YAML
config = AIConfigRuntime.load('travel.aiconfig.json')
config.save("travel.aiconfig.yaml", mode="yaml")

# load and save YAML
config = AIConfigRuntime.load('travel.aiconfig.yaml')
config.save(mode="yaml")

# Default save to JSON
config.save()
config.save("travel2.aiconfig.json")
```
