### ISSUE TITLE
[python] Can't import llama_cpp in llama extension

### ISSUE THREAD

**Issue by rossdanlm** [lastmile-ai/aiconfig#606]
I pip installed the modules from `requirements.txt`, including `llama-cpp-python`, but the module still gives error. Looked at GH and seems like it's not a module: https://github.com/ggerganov/llama.cpp

Read through PyPi for this and it said it's a wrapper: https://pypi.org/project/llama-cpp-python/

I suspect when Jonathan first built this, he has other env/modules already setup but there's nothing in the README to tell people what they need to do: https://github.com/lastmile-ai/aiconfig/blob/main/extensions/llama/python/README.md

**Comment by jonathanlastmileai** [comment]
I couldn't reproduce this. I confirmed that package is correct and was able to run the cookbook in a fresh conda environment.

```
% pip list | grep llama
llama_cpp_python             0.2.25
python-aiconfig-llama        0.0.1
```

```
% python cookbooks/llama/python/ask_llama.py
...
Here are ten interesting things to do in New York City:
...
```

Here are the steps I took to repro:

```
cd ~
conda create -n 606_repro python=3.10 ipykernel
conda activate 606_repro
pip install python-aiconfig python-aiconfig-llama
cp /path/to/aiconfig/cookbooks/llama/python/ask_llama.py .
# [update the cookbook file to point to the correct relative aiconfig and model paths]
 % python ask_llama.py
```

**Comment by rossdanlm** [comment]
Hey sorry, re-opening becuase I'm still getting this module import error

<img width="547" alt="Screenshot 2023-12-26 at 22 03 20" src="https://github.com/lastmile-ai/aiconfig/assets/151060367/97f964fd-248d-41a8-ac27-9deb16f7f39c">

I didn't use `conda create`, only did directly from Jupyter notebook trying to use the `ask_llama.ipynb` file.

I get the same as you when doing pip list:
```
rossdancraig@Rossdans-MacBook-Pro aiconfig % pip list | grep llama
llama_cpp_python                0.2.25
python-aiconfig-llama           0.0.1
```

**Comment by jonathanlastmileai** [comment]
Ok I'm going to reopen and try to repro this again based on your latest comment.

**Comment by jonathanlastmileai** [comment]
OK, I tried a few more things and still can't repro this. I'm going to pass you the issue to add more specific repro steps.

I was able to run the script outside any conda env with my brew python installation after following the readme. I was *not* able to reproduce `no module named llama`. 

I was able to reproduce "can't import llama_cpp" when python-aiconfig is installed but python-aiconfig-llama is not. In this case, the interpreter sees the llama.py module in the same directory as the ipynb but then fails on the llama_cpp import. This is expected, and I dont think explains the missing `llama` module error.

**Comment by rossdanlm** [comment]
Thanks for the deep investigation @jonathanlastmileai 

It turns out the issue was on my end because I had the wrong python kernel. Once I switched it to the one that matched my system it worked!!!
<img width="1920" alt="Screenshot 2023-12-28 at 14 26 17" src="https://github.com/lastmile-ai/aiconfig/assets/151060367/659483ad-8109-4889-9a91-b6897de4cf04">
