### ISSUE TITLE
Error Handling for Dall-E multiple image outputs

### ISSUE THREAD

**Issue by rossdanlm** [lastmile-ai/aiconfig#720]
See comments in https://github.com/lastmile-ai/aiconfig/pull/717#discussion_r1440041484

Dall-E 3 only supports 1 image now, so we should raise a `ValueError` saying so, with link to the API docs: https://platform.openai.com/docs/api-reference/images/create. This should be very similar to what we did in https://github.com/lastmile-ai/aiconfig/pull/687. 

## Testing
To test, we can do two things:
### Test manually 

1. I modified the getting started cookbook (https://github.com/lastmile-ai/aiconfig/blob/main/cookbooks/Getting-Started/getting_started.ipynb) and ran the first few cells to see what the results were. It will output a fileURI that you can enter into a browser and see an image
2. You will have to comment out the line `!pip install python-aiconfig` from the `ipynb` file and install run `pip install -e .` from the `aiconfig/python` dir. This will link the pip module `aiconfig-python` to your local version (the `-e` flag stands for "editing"). You can make sure that this is connected to your path by doing `pip3 list | grep aiconfig` and seeing if `aiconfig-python` points to a path. If it does not, you need to do `pip3 uninstall aiconfig-python` and then do `pip3 install -e .` like mentioned earlier
3. You can see some changes I did to the `travel.aiconfig.json` file in screenshot in https://github.com/lastmile-ai/aiconfig/pull/288 to see what I changed to get it to run
4. You can also see a bit on how I changed the `ipynb` notebook in https://github.com/lastmile-ai/aiconfig/pull/298

### Automated Testing 
Create dependent issue for this in https://github.com/lastmile-ai/aiconfig/issues/741
1. Add automated testing for Dall-E 2, similar to what we have for Dall-E 3: https://github.com/lastmile-ai/aiconfig/pull/294. This only tests for load and `serialize` functions though
2. Add automated test for the `run()` command. This is a bit less well defined and I will need to give you some codepointers here on how to get started

**Comment by rossdanlm** [comment]
May be related to https://github.com/lastmile-ai/aiconfig/issues/721

**Comment by Ankush-lastmile** [comment]
<img width="1195" alt="Screenshot 2024-01-11 at 2 00 28 PM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/8257048a-6155-473c-ba21-b244ef900193">

The openai sdk already throws a reasonable error when n is > 1. Closing because openai's error is enough to bubble up
